In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
housing = pd.read_csv("house_pricing.csv")
housing

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


housingMedianAge  totalRooms  ...  medianIncome  medianHouseValue
0                  41.0       880.0  ...        8.3252          452600.0
1                  21.0      7099.0  ...        8.3014          358500.0
2                  52.0      1467.0  ...        7.2574          352100.0
3                  52.0      1274.0  ...        5.6431          341300.0
4                  52.0      1627.0  ...        3.8462          342200.0
...                 ...         ...  ...           ...               ...
20635              25.0      1665.0  ...        1.5603           78100.0
20636              18.0       697.0  ...        2.5568           77100.0
20637              17.0      2254.0  ...        1.7000           92300.0
20638              18.0      1860.0  ...        1.8672           84700.0
20639              16.0      2785.0  ...        2.3886           89400.0

[20640 rows x 7 columns]

In [11]:
housing.describe().transpose()

count           mean  ...           75%          max
housingMedianAge  20640.0      28.639486  ...      37.00000      52.0000
totalRooms        20640.0    2635.763081  ...    3148.00000   39320.0000
totalBedrooms     20640.0     537.898014  ...     647.00000    6445.0000
population        20640.0    1425.476744  ...    1725.00000   35682.0000
households        20640.0     499.539680  ...     605.00000    6082.0000
medianIncome      20640.0       3.870671  ...       4.74325      15.0001
medianHouseValue  20640.0  206855.816909  ...  264725.00000  500001.0000

[7 rows x 8 columns]

In [12]:
summary = housing.describe()
summary = summary.transpose()
print(summary)
X = housing.drop(['medianHouseValue'],axis=1)
y = housing['medianHouseValue']

                    count           mean  ...           75%          max
housingMedianAge  20640.0      28.639486  ...      37.00000      52.0000
totalRooms        20640.0    2635.763081  ...    3148.00000   39320.0000
totalBedrooms     20640.0     537.898014  ...     647.00000    6445.0000
population        20640.0    1425.476744  ...    1725.00000   35682.0000
households        20640.0     499.539680  ...     605.00000    6082.0000
medianIncome      20640.0       3.870671  ...       4.74325      15.0001
medianHouseValue  20640.0  206855.816909  ...  264725.00000  500001.0000

[7 rows x 8 columns]


In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scale = scaler.fit_transform(X)
x_scale

array([[0.78431373, 0.02233074, 0.01986344, 0.00894083, 0.02055583,
        0.53966842],
       [0.39215686, 0.18050257, 0.17147734, 0.0672104 , 0.18697583,
        0.53802706],
       [1.        , 0.03726029, 0.02932961, 0.01381765, 0.02894261,
        0.46602805],
       ...,
       [0.31372549, 0.05727657, 0.07510863, 0.0281398 , 0.07104095,
        0.08276438],
       [0.33333333, 0.04725571, 0.06331471, 0.02068444, 0.05722743,
        0.09429525],
       [0.29411765, 0.07078183, 0.09543762, 0.03879032, 0.08699227,
        0.13025338]])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_scale,y,test_size = 0.2,random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_test

array([[-0.52529688, -0.24653996, -0.32890798,  0.10985054, -0.33558946,
         0.14448941],
       [ 0.26831504, -0.00920984, -0.33127613, -0.11324108, -0.18394407,
         0.99820424],
       [ 0.03023146,  0.24092422,  0.02394501,  0.11247515,  0.09058637,
         0.24775544],
       ...,
       [-1.39827   , -0.42076496, -0.45678759, -0.5034327 , -0.45324536,
        -0.35327491],
       [-0.84274165,  0.0452069 , -0.34311683, -0.30921176, -0.32774573,
         1.18910742],
       [ 1.85553889, -0.48478465, -0.26496818,  0.03198719, -0.24407931,
        -0.28514765]])

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense
ann = Sequential()
ann.add(Dense(7,input_dim = 6, activation='relu'))
ann.add(Dense(3, activation='relu'))
ann.add(Dense(1, activation='linear'))
ann.compile(optimizer="Adam", loss='mean_squared_error', metrics=['accuracy'])
# ann.fit(X_train, y_train, batch_size = 20, epochs = 100)
ann.fit(X_train,y_train, epochs=1000, verbose=1)

Epoch 1/1000
16512/16512 [==============================] - 1s 81us/step - loss: 56332769347.4729 - accuracy: 0.0000e+00
Epoch 2/1000
16512/16512 [==============================] - 1s 79us/step - loss: 56282571339.4109 - accuracy: 0.0000e+00
Epoch 3/1000
16512/16512 [==============================] - 1s 77us/step - loss: 56107029535.7519 - accuracy: 0.0000e+00
Epoch 4/1000
16512/16512 [==============================] - 1s 76us/step - loss: 55747956426.4186 - accuracy: 0.0000e+00
Epoch 5/1000
16512/16512 [==============================] - 1s 76us/step - loss: 55153324032.0000 - accuracy: 0.0000e+00
Epoch 6/1000
16512/16512 [==============================] - 1s 78us/step - loss: 54321867307.6589 - accuracy: 0.0000e+00
Epoch 7/1000
16512/16512 [==============================] - 1s 75us/step - loss: 53249433508.7132 - accuracy: 0.0000e+00
Epoch 8/1000
16512/16512 [==============================] - 1s 76us/step - loss: 51937211753.1783 - accuracy: 0.0000e+00
Epoch 9/1000
16512/16512 [======

In [17]:
y_pred = ann.predict(X_test)
y_pred 

array([[162445.89],
       [286463.03],
       [216446.16],
       ...,
       [143312.89],
       [275593.34],
       [209243.08]], dtype=float32)

In [29]:
ann.predict_proba([[[41,880,129,322,126,8]]])[0][0]

/usr/local/lib/python3.6/dist-packages/keras/engine/sequential.py:248: UserWarning: Network returning invalid probability values. The last layer might not normalize predictions into probabilities (like softmax or sigmoid would).
  warnings.warn('Network returning invalid probability values. '


8101016.5

In [33]:
score = ann.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])

Test loss: 5576765747.596899


In [34]:
import joblib
joblib.dump(ann, "housing_price_prediction.pkl")

['housing_price_prediction.pkl']